#!/usr/bin/env bash

# expand includes of last modified .cpp file and copies to clipboard or to a file
LAST_MODIFIED="$(fd -Iae cpp -x stat --format '%Y %n' {} \; | sort -nr | head -1 | cut -d' ' -f2-)"
if [ -z "$1" ]; then
  python3 script/expand_include.py $LAST_MODIFIED | xclip -selection clipboard
else
  python3 script/expand_include.py $LAST_MODIFIED >"$1"
fi

